"""Rename users table

Revision ID: 5abe808a023a
Revises: 0992feb800ca
Create Date: 2023-05-23 10:28:53.156901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5abe808a023a'
down_revision = '0992feb800ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('users', 'user')
    op.execute('ALTER INDEX users_pkey RENAME TO user_pkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'users')
    op.execute('ALTER INDEX user_pkey RENAME TO users_pkey')
    # ### end Alembic commands ###
